Add k8s 1.25.14
rancher/hyperkube pull request #329
Opened 2023-09-14 14:01 UTC by chiukapoor

## Updates
- K8s: v1.25.14

## Issue
- https://github.com/rancher/rancher/issues/42812
- https://github.com/rancher/rancher/issues/42813

2023-09-18 21:38 UTC, jiaqiluo requested changes
Please ping me after the tag is released in `rancher/kubernetes` and the Drone CI passes here.

2023-09-19 02:53 UTC, snasovich approved these changes
LGTM once CI passes

2023-09-22 06:36 UTC, rayandas commented
@jiaqiluo Could you please approve the PR so that we can merge it and tag?

2023-09-22 16:05 UTC, jiaqiluo approved these changes

2023-09-25 04:32 UTC, merged